#:schema node_modules/wrangler/config-schema.json
name = "storage"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

account_id = ""
workers_dev = true

[[r2_buckets]]
binding = 'R2'
bucket_name = ''
preview_bucket_name = ''

[vars]
KEY = ''
