# This is a config for E2B sandbox template.
# You can use 'template_id' (9wd4o5v55nc2edgak6vv) or 'template_name (gitwit-reactjs) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='gitwit-reactjs')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'gitwit-reactjs' })

team_id = "34eab90a-97dc-4be5-87e3-a17b6e6e8bc6"
dockerfile = "e2b.Dockerfile"
template_name = "gitwit-reactjs"
template_id = "9wd4o5v55nc2edgak6vv"
